name: Nix

on:
  push:
    branches:
      - main
    paths:
      - flake.nix
      - flake.lock
      - nix/**
      - Cargo.toml
      - Cargo.lock
  pull_request:
    paths:
      - flake.nix
      - flake.lock
      - nix/**
      - Cargo.toml
      - Cargo.lock

permissions:
  contents: read

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Cache Nix builds
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Check flake
        run: nix flake check
